name: Project Continuous Integration

on:
  push:
    branches: ["main", "docker", kubernetes]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ./vendor
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run Tests
        run: |
          go test ./...

      - name: Build Go App
        run: |
          go build -o myapp

      - name: Run Gin Server
        run: |
          nohup ./myapp & # Rodando em segundo plano

      - name: Verify Server is Running
        run: |
          curl --fail http://localhost:8080 || exit 1
